### ISSUE TITLE
Stats mixing

### ISSUE THREAD

**Issue by EmilLa1** [Concordium/concordium-network-dashboard#106]
**Bug Description**
When peers from two different chains reports to the dashboard it sometimes shows data from the chain that it should not. 

**Steps to Reproduce**
- Go to e.g. https://dashboard.testnet.concordium.com/
- Stare at your screen.

**Expected Result**
The mixed data does not appear. 

**Actual Result**
The data from the old chain appears once in a while. 

Chrome on Ubuntu. 

![Screenshot from 2022-06-13 14-21-49](https://user-images.githubusercontent.com/39825288/173359407-6334d00e-6613-4509-9cae-05d42da9f7f4.png)

**Comment by abizjak** [comment]
I don't think this is a network dashboard bug as such. To me it looks like there was a deployment issue where the relevant caches were not cleared.

Since the network dashboard requests peer data every so often, it seems like it sometimes got the old data. I could observe this as well, but I can no longer see it after whatever caches were 

Thus I am inclined to close this issue since I don't think there is anything that should be done for the network dashboard itself.

**Comment by EmilLa1** [comment]
I have now stared at my screen for several minutes and I think your are right. I will close the issue for now.

**Comment by bisgardo** [comment]
I assume that "data from the old chain" is referring to the stats at the top? I believe that all the stats are computed as the median of the reported values. So I can't see how it's a deployment issue but rather a result of less than half of the nodes (19/42) being upgraded at the time of the screenshot.

I'm not sure why only the finalization values are off, maybe they aren't computed in the same way.

I think it would make sense to update the logic somehow to filter out the data of old nodes.

**Comment by abizjak** [comment]
We already have the logic for filtering data from old nodes in the statistics calculations.

**Comment by bisgardo** [comment]
Ok I see that's implemented using an env var `MIN_VERSION_INCLUDED_IN_STATS`. The deployment doesn't currently set that value.

**Comment by EmilLa1** [comment]
Just to be clear: It's as such not only related to finalization data. When I stared at the screen long enough I also observed skewed heights.

**Comment by bisgardo** [comment]
Or is it the thing where it has to be provided on build time?

**Comment by abizjak** [comment]
It is the one that has to be provided at build time.
