### ISSUE TITLE
Support displaying NotAllowedToHandleEncrypted reject reason

### ISSUE THREAD

**Issue by orhoj** [Concordium/concordium-network-dashboard#11]
**Bug Description**
The block explorer fails to correctly parse a rejected transaction, where the reason is that the account is not allowed to handle encrypted transfers.

**Steps to Reproduce**
On a chain create an account and add an additional credential to that account. Then try to send some GTU to the encrypted balance for that account. This will fail and the error can be seen in the network dashboard. I performed the above on the stagenet.

**Expected Result**
The network dashboard should parse the reject reason correctly, and display a nice error message that the users can understand.

**Actual Result**
The network dashboard fails when parsing the JSON:

Error: Json.Decode.oneOf failed in the following 3 ways: (1) The Json.Decode.oneOf at json.outcomes.e886d9f4767fdc10cb6dcf95fe5af564362ae9890c8305be566f78a8847b28bd.result failed in the following 2 ways: (1) Problem with the given value: { "outcome": "reject", "rejectReason": { "tag": "NotAllowedToHandleEncrypted" } } Expecting an OBJECT with a field named `events` (2) Problem with the value at json.rejectReason: { "tag": "NotAllowedToHandleEncrypted" } Unknown RejectReason: NotAllowedToHandleEncrypted (2) Problem with the given value: { "status": "finalized", "outcomes": { "e886d9f4767fdc10cb6dcf95fe5af564362ae9890c8305be566f78a8847b28bd": { "hash": "f69005a3e78fee1d3b539ddc5f47c3770773367188ea0c39c52cc4bf0421bb4f", "sender": "4bJ8rG6cf7i84MZky3L1kY9fEN9NvTWdAT3frxHs4vCVd7TLDT", "cost": "76900", "energyCost": 769, "result": { "outcome": "reject", "rejectReason": { "tag": "NotAllowedToHandleEncrypted" } }, "type": { "contents": "transferToEncrypted", "type": "accountTransaction" }, "index": 0 } } } Expecting a STRING (3) Problem with the given value: { "status": "finalized", "outcomes": { "e886d9f4767fdc10cb6dcf95fe5af564362ae9890c8305be566f78a8847b28bd": { "hash": "f69005a3e78fee1d3b539ddc5f47c3770773367188ea0c39c52cc4bf0421bb4f", "sender": "4bJ8rG6cf7i84MZky3L1kY9fEN9NvTWdAT3frxHs4vCVd7TLDT", "cost": "76900", "energyCost": 769, "result": { "outcome": "reject", "rejectReason": { "tag": "NotAllowedToHandleEncrypted" } }, "type": { "contents": "transferToEncrypted", "type": "accountTransaction" }, "index": 0 } } } Expecting null

**Versions**
- Software Version: Network dashboard currently running on stagenet (it does not display its version as far as I can see, perhaps it should?)
- OS: Ubuntu
- Browser: Chrome Version 89.0.4389.114 (Official Build) (64-bit)
- Mobile device, if applicable: N/A

**Comment by amaurremi** [comment]
Note: this can also be reproduced by looking up transaction [f69005a3e78fee1d3b539ddc5f47c3770773367188ea0c39c52cc4bf0421bb4f](http://dashboard.eu.staging.concordium.com/lookup/f69005a3e78fee1d3b539ddc5f47c3770773367188ea0c39c52cc4bf0421bb4f)
