### ISSUE TITLE
Simple transfers from contracts should be paged

### ISSUE THREAD

**Issue by Bargsteen** [Concordium/concordium-network-dashboard#14]
**Description**
`simple_transfer`s from smart contracts should be paged similarly to how regular transactions are paged.
The unpaged behaviour becomes an issue for contracts with large action trees that produce simple transfers.

Example of current behaviour:
![image](https://user-images.githubusercontent.com/5469652/117150120-261db180-adb8-11eb-8274-bd6a70c66631.png)

**Comment by abizjak** [comment]
A small addition, I think it should not just be for simple-transfers, because you can in principle have large sequences of `update` events inside one smart contract transaction call.
