### ISSUE TITLE
`NotAllowedMultipleCredentials` not parsed correctly

### ISSUE THREAD

**Issue by Bargsteen** [Concordium/concordium-network-dashboard#20]
**Bug Description**
Parsing a transaction summary with a `NotAllowedMultipleCredentials` fails.

**Steps to Reproduce**
View https://dashboard.eu.staging.concordium.com/chain/296fb92df10d924123435f95d72ab7c1eb519e5714da1015c5e834ff898d40d6

Or try to add a credential to an account with a non-zero encrypted amount.

**Expected Result**
The reject reason should be parsed and shown correctly.

**Actual Result**
![image](https://user-images.githubusercontent.com/5469652/118466253-f600d780-b702-11eb-811c-90f972251902.png)

**Versions**
- Software Version: Dashboard on stagenet
- OS: MacOS
- Browser: Brave

**Comment by abizjak** [comment]
I think you fixed this @amaurremi 

I think the version on stagenet is quite old by now.

**Comment by amaurremi** [comment]
Yes, it should work. 
![Screenshot from 2021-05-17 14-17-30](https://user-images.githubusercontent.com/394853/118487151-b645ea00-b71a-11eb-8354-eaf9118dec3e.png)

**Comment by abizjak** [comment]
Ok, closing since it's already fixed in `main`.
