### ISSUE TITLE
Displaying foundation account update not supported

### ISSUE THREAD

**Issue by amaurremi** [Concordium/concordium-network-dashboard#21]
**Bug Description**
Updating the foundation account results in a JSON parse error.

**Steps to Reproduce**
View block [2879c611d9fb82200d9f6be75d3649b838f275d210473a83fd68dec4d227c823](https://dashboard.eu.staging.concordium.com/chain/2879c611d9fb82200d9f6be75d3649b838f275d210473a83fd68dec4d227c823).

**Expected Result**
A message saying that the foundation account was updated.

**Actual Result**
![Screenshot from 2021-05-17 14-21-10](https://user-images.githubusercontent.com/394853/118488364-f35eac00-b71b-11eb-924f-354bb153275a.png)

**Comment by limemloh** [comment]
Fixed by #22
