### ISSUE TITLE
Several minor issues with text being written vertically

### ISSUE THREAD

**Issue by Bargsteen** [Concordium/concordium-network-dashboard#24]
**Bug Description**
Several different types are written vertically. Seems like the horizontal space allowed is too little. There are likely more cases. these are just the ones I've found.

**Baker account address**
![image](https://user-images.githubusercontent.com/5469652/118767305-d6da8500-b87d-11eb-8517-e7f3a7938b51.png)
https://dashboard.testnet.concordium.com/chain/ef09010ca573602a53736e85b30f979ed22b8000f6e35885b0e0bc30d7b884a8
https://dashboard.testnet.concordium.com/chain/05f3b0a74f80a6d3c2a51f3c66b9edf5f9a6a8b43b7ca0db34a0c742e1ad301e

**Module references**
![image](https://user-images.githubusercontent.com/5469652/118772052-93831500-b883-11eb-9b99-d48a8ab27152.png)
https://dashboard.testnet.concordium.com/chain/d247992c27beddf7d5c18144959603075d29e89cf9cf13e13a7b6708eb7c7506

**Contract Address**
![image](https://user-images.githubusercontent.com/5469652/118772149-b1507a00-b883-11eb-8187-6d7688043d99.png)
https://dashboard.testnet.concordium.com/chain/81e7f27e853c8b2bafafd731f276e8e75613e510298bc32d1ab2957d7f002cea

**Account address**
![image](https://user-images.githubusercontent.com/5469652/118772294-e1981880-b883-11eb-9b41-a9e42d88daf9.png)
https://dashboard.testnet.concordium.com/chain/6d18305a2742fd223f1dcc785e2acae2d472b21ca13b3f43f65e180241657001

*Note that account addresses are shown correctly in the tokenomics section.*
![image](https://user-images.githubusercontent.com/5469652/118772479-13a97a80-b884-11eb-929a-48e4b32e5591.png)

**Versions**
- Software Version: Version currently on testnet
- OS: Linux
- Browser: Brave

**Comment by limemloh** [comment]
This was fixed in #18
