### ISSUE TITLE
Dashboard should have version number

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-network-dashboard#26]
**Bug Description**
The dashboard must have a version number.

**Comment by abizjak** [comment]
@limemloh This has been fixed right? Can you please close this issue if that is the case.

**Comment by concordium-cl** [comment]
I cannot see any version number on the network dashboard.

**Comment by limemloh** [comment]
It should show up next to the Concordium logo in the top right corner. It was fixed in PR #27.
But it is not release yet
