### ISSUE TITLE
Two green blocks showed in block explorer

### ISSUE THREAD

**Issue by eb-concordium** [Concordium/concordium-network-dashboard#28]
**Bug Description**
A fork with two green blocks was found in the block explorer.

**Steps to Reproduce**
Not very clear. Only discovered this once.

**Expected Result**
No more than one green block per fork.

**Actual Result**
Two green blocks in a fork, as in the below picture

**Version
- Browser: Google Chrome
![dashboard](https://user-images.githubusercontent.com/77331975/119110512-86505c80-ba22-11eb-99a4-03a718defec7.png)

**Comment by abizjak** [comment]
This is a known issue with the network dashboard.

It will show all branches behind the last finalized block as green.

This has been reported at least 3 times in the past on JIRA :) so it is perhaps good that it is now also in the issues.

**Comment by Bargsteen** [comment]
Closed by https://github.com/Concordium/concordium-network-dashboard/pull/48
