### ISSUE TITLE
Long smart contract logs overflow

### ISSUE THREAD

**Issue by limemloh** [Concordium/concordium-network-dashboard#40]
**Bug Description**
If a smart contract logs a big enough event, it will overflow in the UI

**Actual Result**
![image](https://user-images.githubusercontent.com/6437768/124598771-4542c900-de65-11eb-8fc0-071d645cec6d.png)

**Comment by abizjak** [comment]
@eulervoid this has unfortunately not been fixed by the latest PR. The contract events emitted still overflows.

Here is the link on the testnet http://dashboard.testnet.concordium.com/chain/d91cdd8d5a908bc91f9e751cd08e6ad627169747460e82a572a592b7b2e4427d to the block with the summary
