### ISSUE TITLE
Credential Update Display Issue

### ISSUE THREAD

**Issue by tschudid** [Concordium/concordium-network-dashboard#5]
**Bug Description**
Layout breaks when reporting on a credential update.

<img width="1651" alt="Screen Shot 2021-04-23 at 16 35 37" src="https://user-images.githubusercontent.com/14889202/115888478-42822b80-a453-11eb-80e9-313465f5898b.png">

**Steps to Reproduce**

Send a credential update to the chain.

**Expected Result**

Dashboard nicely displays that a credential update happened.

**Actual Result**

Dashboard layout overflows.

**Comment by amaurremi** [comment]
Fix #6 introduced a new problem in which account addresses are split into multiple lines.
![Screenshot from 2021-05-06 16-13-51](https://user-images.githubusercontent.com/394853/117319810-f17b2a00-ae8b-11eb-99bb-745e1a95bbb7.png)
I'm working on fixing it.
