### ISSUE TITLE
Explain what the purple bars on blocks mean

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-network-dashboard#53]
**Task description**

On the chain visualisation page some of the blocks have purple bars on them, but it is not explain anywhere what these mean.
We should add a way to display a text explaining what they mean, either in the form of a mouseover or an "i" icon like for "Finalization Time'.

Since these bars move it is important to ensure good experience where the text does not randomly disappear because of the update of the visualisation.

The text should say something like (it depends a bit on where it will appear)

"The proportion of nodes which have this block as the best block."

If the text will not be a hover over the bar itself, but somewhere else, then a more appropriate text would be

"The purple bars represent the proportion of the nodes which have the given block as the best block."

**Comment by eulervoid** [comment]
Hey, i had a look at this and would propose two different solutions. 
The simplest i can think of is a sort of legend, with which we could use the tooltips as they are already implemented. For consistency, i would then also include the other colors and explain what they mean. Like this: 

![Legend](https://user-images.githubusercontent.com/3340175/130077903-d9c9337c-3ba9-4f4b-a5ef-72d749ac88d4.png)

Another option i see working well is an info bar at the top that shows up when the user hovers over one of the pink bars. This would be a litte more effort as it involves a new message and animation, but i think it would look nice. I imagine it like this: 

![Infobar](https://user-images.githubusercontent.com/3340175/130078069-e7461046-d050-4e4d-8e54-01c84194c97d.png)

Let me know which you like better.

**Comment by limemloh** [comment]
I would prefer the first option, and maybe just with one info button, which will display an image with a small example chain and an explanation of the whole chain view.

The second option would look neat, but I think it might be a bad experience to have hover triggers on moving parts.
Especially since the purple bar is not that big of a target.

**Comment by abizjak** [comment]
I favor the first proposal (with the full legend as you suggest) since the bars are dynamic and I think it'll be confusing, with both the bar and the blocks moving.

So let's go for that.

**Comment by abizjak** [comment]
Resolved by #55.
