### ISSUE TITLE
Long memo text shown in one long line

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-network-dashboard#59]
**Bug Description**
Long memo text in transaction lookup and block explorer on dashboard overflows box

**Steps to Reproduce**
* make transaction with long memo text
* observe dashboard

e.g. 
* http://dashboard.stagenet.concordium.com/chain/3912a505054dfc21cb918923c359a87a8b378b2f05e98beb9f64d851116e37f1
 
![block explorer](https://user-images.githubusercontent.com/69570978/132514558-6c05b2f0-b378-4941-ab64-38cf1d0a359f.JPG)
![transaction lookup](https://user-images.githubusercontent.com/69570978/132514570-5a244f22-ab3d-4a02-9719-7ca94b82b347.JPG)

**Expected Result**
* Text is shown with line breaks to fit in box.

**Actual Result**
* Text is shown in one line and overflows the box.

**Versions**
- windows
- google chrome
- network dashboard version: 1.0.1
- client version 1.1.0

**Comment by eulervoid** [comment]
This is probably just missing a `paragraph [] [...]`. Should i go ahead and fix it?

**Comment by abizjak** [comment]
@eulervoid Yes please :)

**Comment by eulervoid** [comment]
I think i might have solved this, but i don't have access to a stagenet to test, is there any way to find a block that contains actual transactions in testnet or mainnet?

**Comment by abizjak** [comment]
No, this is not enabled on those networks yet. If you make a PR I'll test it tomorrow.

**Comment by abizjak** [comment]
Closed by #62
