### ISSUE TITLE
Error message & icon for failed transaction could be improved

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-network-dashboard#60]
**Bug Description**
For a too long memo text, the dashboard shows the following 

![failed_transaction](https://user-images.githubusercontent.com/69570978/132515194-f3d7f4c0-471c-45a1-823c-550f30e41279.JPG)

* The text could be more informative.
* A red transaction icon is missing.

**Steps to Reproduce**
* Make a transaction with a too long memo text.

e.g. https://dashboard.stagenet.concordium.com/chain/64a0a288bc35a6e13198cfa44a0b3cba09c887ff03b237a8eb9133267fb2ac07

**Expected Result**
* Reason for failure given.
* Transfer icon in red.

**Actual Result**
See screenshot.

**Versions**
* windows
* google chrome
* network dashboard version: 1.0.1
* client version 1.1.0

**Comment by abizjak** [comment]
That is the reason for failure that is given by the node. So the network dashboard cannot do better here.

**Comment by abizjak** [comment]
So I recommend closing this since to fix it would mean fairly significantly changing how the node handles this invalid case.

**Comment by abizjak** [comment]
This case should be prevented by the wallets, they should simply not allow sending memos that are invalid.

**Comment by concordium-cl** [comment]
But the client allows it.

**Comment by abizjak** [comment]
Yes, which is the thing that should be fixed.

**Comment by concordium-cl** [comment]
Changed issue https://github.com/Concordium/concordium-client/issues/68 accordingly.
