### ISSUE TITLE
Display gtu/EUR conversion rate better

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-network-dashboard#67]
**Description**

The conversion rate between microGTU and EUR is displayed as is, which is hard to read, e.g., see 
https://dashboard.mainnet.concordium.software/chain/36a1e4ea1f0e9e125f7831e41e71ca7ae5562c7052ec226e15b0624e9204cbbd

![Screenshot from 2021-09-20 08-09-03](https://user-images.githubusercontent.com/105212/133962405-00206412-7c6b-47b0-a689-2df0fd9098c5.png)

It would be better to display it as GTU/EUR, so in the linked example it would say "2.777778 GTU per EUR" or "1 EUR = 2.777778 GTU".

**Versions**
- Software Version: 1.0.0-1.0.2

**Comment by concordium-cl** [comment]
Use "1 EUR = 2.777778 GTU".
